---
title: "153-ancients-structure"
author: "Kushal K Dey"
date: "September 21, 2016"
output: html_document
---

## Packages + Scripts

We load the packages and source the scripts we would need for the analysis of the 153 ancients data.

```{r echo=TRUE, eval=TRUE}
## the above scripts will eventually be part of flashr package
source("../R/visDMsignature.R")

## will eventually be part of the damage signature package

##  The libraries we need 

library(CountClust)
library(ggplot2)
library(pmsignature)
library(flashr)
```


Some helper functions we need 

```{r echo=TRUE, eval=TRUE}
gsub2 <- function(pattern, replacement, x, ...) {
  for(i in 1:length(pattern))
    x <- gsub(pattern[i], replacement[i], x, ...)
  x
}
```

```{r echo=TRUE, eval=TRUE}
signature_counts <- get(load("../summary_data/153-ancients-counts-table.rda"))

signature_set <- colnames(signature_counts)

## dimensions of data: nrows=number of samples 
## ncols = number of damage/mutation signatures

print(dim(signature_counts))

## the top corner of the counts matrix

signature_counts[1:5,1:5]
```

Applying PCA on the data 

```{r}
voom_signature_counts <- t(limma::voom(t(signature_counts))$E);
voom_weights <- t(limma::voom(t(signature_counts))$weights);

pr <- prcomp(voom_signature_counts)

pc_data_frame <- data.frame("PC"=pr$x,
                            "labels"=c(rep("I",38), rep("RISE",27)))

graphList <- vector(mode="list");
library(ggplot2)


graphList[[1]] <- qplot(PC.PC1, PC.PC2,
      data=pc_data_frame,
      colour=labels)

graphList[[2]] <-qplot(PC.PC1, PC.PC3,
      data=pc_data_frame,
      colour=labels)

graphList[[3]] <-qplot(PC.PC2, PC.PC3,
      data=pc_data_frame,
      colour=labels)

library(grid)
library(gridExtra)
a <- do.call("grid.arrange", 
               args = list(grobs=graphList,
                            ncol = 2,
                            nrow = 2))



```

Applying CountClust 

```{r echo=FALSE, eval=FALSE}
topics_clus <- maptpx::topics(signature_counts, K=3, tol=0.01);
save(topics_clus, file="../rda/topics-153-ancients-k-3-countclust.rda")

topics_clus <- maptpx::topics(signature_counts, K=2, tol=0.01);
save(topics_clus, file="../rda/topics-153-ancients-k-2-countclust.rda")
```

```{r}
topics_clus <- get(load("../rda/topics-153-ancients-k-2-countclust.rda"))

omega <- topics_clus$omega

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(c(rep("I",38), rep("RISE",27)))
)

rownames(omega) <- annotation$sample_id;

StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Moderns vs Ancients",
                order_sample = TRUE,
                figure_title = paste0("StructurePlot: K=", dim(omega)[2],": pmsignature: with C->T/G->A"),
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

apply(ExtractTopFeatures(topics_clus$theta, top_features = 10, method="poisson", options="min"), c(1,2), function(x) signature_set[x])


```

```{r}
topics_clus <- get(load("../rda/topics-153-ancients-k-3-countclust.rda"))

omega <- topics_clus$omega

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(c(rep("I",38), rep("RISE",27)))
)

rownames(omega) <- annotation$sample_id;

StructureGGplot(omega = omega,
                annotation = annotation,
                palette = RColorBrewer::brewer.pal(8, "Accent"),
                yaxis_label = "Moderns vs Ancients",
                order_sample = TRUE,
                figure_title = paste0("StructurePlot: K=", dim(omega)[2],": pmsignature: with C->T/G->A"),
                axis_tick = list(axis_ticks_length = .1,
                                 axis_ticks_lwd_y = .1,
                                 axis_ticks_lwd_x = .1,
                                 axis_label_size = 7,
                                 axis_label_face = "bold"))

apply(ExtractTopFeatures(topics_clus$theta, top_features = 10, method="poisson", options="min"), c(1,2), function(x) signature_set[x])


```

Merging this data with Lindo 2016 data.

```{r}
lindo_signature_counts <- get(load("../summary_data/signature-counts-clubbed-Lindo2016.rda"))
```

